[helpers]

[default]
depends = ["shell", "wm"]

[default.files]
"scripts" = "~/.scripts"
"wallpaper" = "~/wallpaper"

[default.variables]
WALLPAPER_VIDEO = ""

[shell.files]
"config/zsh" = "~/.config/zsh"
"config/zellij" = "~/.config/zellij"
"config/yazi" = "~/.config/yazi"
"config/lazygit" = "~/.config/lazygit"

[wm.files]
"config/kitty" = "~/.config/kitty"
"config/environment.d" = "~/.config/environment.d"
"config/xsettingsd" = "~/.config/xsettingsd"
"config/gtk-3.0" = "~/.config/gtk-3.0"
"config/gtk-4.0" = "~/.config/gtk-4.0"
"config/niri" = "~/.config/niri"
"config/DankMaterialShell" = "~/.config/DankMaterialShell"
"config/code-flags.conf" = "~/.config/code-flags.conf"
"config/microsoft-edge-stable-flags.conf" = "~/.config/microsoft-edge-stable-flags.conf"

[settings]
default_target_type = "automatic"
